Repository ita-social-projects/EventsExpress, pull requests merged in 2020-12, with the labels that each got.

#293 Fix routing for chat and count of user/events for categories
  EventsExpress.Core/Services/CategoryService.cs
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
  EventsExpress/ClientApp/src/services/ChatService.js
  EventsExpress/Controllers/ChatController.cs
  EventsExpress/Properties/launchSettings.json
Labels: bug, hotfix

#307 Fix mistakes in notification after receiving a new message
  EventsExpress/ClientApp/src/actions/chat.js
  EventsExpress/ClientApp/src/components/chat/user_chats.js
  EventsExpress/ClientApp/src/services/ChatService.js
Labels: bug, hotfix

#306 Spelling mistakes in the confirmation message while user updates personal information
  EventsExpress/ClientApp/src/actions/EditProfile/addUserCategory.js
Labels: bug, hotfix

#308 Fix punctuation error and wrong alignment on the ‘Edit your profile’ page
  EventsExpress/ClientApp/src/components/profile/editProfile/ChangePassword.jsx
  EventsExpress/ClientApp/src/components/profile/profile.js
Labels: bug

#309 Fit list of comments within the text box container on the "detailed event information" page
  EventsExpress/ClientApp/src/components/event/event-item-view.js
Labels: bug

#313 Fix mistake of the title of the checkbox on the new form of the event.
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
Labels: bug

#314 Implement the cancel button
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/eventSchedule/selective-form.js
  EventsExpress/ClientApp/src/components/profile/user-profile.js
  EventsExpress/ClientApp/src/containers/add-event.js
  EventsExpress/ClientApp/src/containers/edit-event-from-parent.js
  EventsExpress/ClientApp/src/containers/edit-event.js
Labels: bug

#318 Fixed: unlimited number of characters for event title
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
  EventsExpress/Validation/EventCreateViewModelValidator.cs
  EventsExpress/Validation/EventEditViewModelValidator.cs
Labels: bug

#317 Limit width of div
  EventsExpress/ClientApp/src/components/chat/user_chats.css
  EventsExpress/ClientApp/src/components/chat/user_chats.js
Labels: bug

#341 Fixed: avability to create duplicate of an existing category
  EventsExpress.Core/IServices/ICategoryService.cs
  EventsExpress.Core/Services/CategoryService.cs
  EventsExpress.Test/ServiceTests/CategoryServiceTest.cs
  EventsExpress/ClientApp/src/actions/category/add-category.js
  EventsExpress/ClientApp/src/actions/category/category-list.js
  EventsExpress/ClientApp/src/actions/category/delete-category.js
  EventsExpress/ClientApp/src/components/Route guard/401.js
  EventsExpress/ClientApp/src/components/category/categories.js
  EventsExpress/ClientApp/src/components/category/category-edit.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
  EventsExpress/ClientApp/src/components/profile/profile.js
  EventsExpress/ClientApp/src/containers/add-event.js
  EventsExpress/ClientApp/src/containers/categories/SelectCategories.js
  EventsExpress/ClientApp/src/containers/categories/category-add.js
  EventsExpress/ClientApp/src/containers/categories/category-item.js
  EventsExpress/ClientApp/src/containers/edit-event-from-parent.js
  EventsExpress/ClientApp/src/containers/edit-event.js
  EventsExpress/ClientApp/src/containers/event-filter.js
  EventsExpress/ClientApp/src/reducers/category/add-category.js
  EventsExpress/ClientApp/src/reducers/category/category-list.js
  EventsExpress/ClientApp/src/reducers/category/category.js
  EventsExpress/ClientApp/src/reducers/category/delete-category.js
  EventsExpress/ClientApp/src/reducers/root.js
  EventsExpress/ClientApp/src/services/CategoryService.js
  EventsExpress/ClientApp/src/services/CommentService.js
  EventsExpress/ClientApp/src/services/EventService.js
  EventsExpress/ClientApp/src/services/UserService.js
  EventsExpress/Controllers/CategoryController.cs
  EventsExpress/Filters/EventsExpressExceptionFilter.cs
  EventsExpress/Mapping/AutoMapperProfile.cs
  EventsExpress/ModelBinders/TrimModelBinder.cs
  EventsExpress/Startup.cs
  EventsExpress/Validation/CategoryCreateViewModelValidator.cs
  EventsExpress/Validation/CategoryDtoValidator.cs
  EventsExpress/Validation/CategoryEditViewModelValidator.cs
  EventsExpress/ViewModels/CategoryCreateViewModel.cs
  EventsExpress/ViewModels/CategoryEditViewModel.cs
Labels: Refactoring, bug

#349 Added closing in a state when press the confirm button in the modal.
  EventsExpress/ClientApp/src/components/event/simple-modal.js
Labels: bug
