Repository ita-social-projects/EventsExpress, pull requests merged in 2020-11, with the labels that each got.

#147 Edit onSubmit method in add-event.js
  EventsExpress/ClientApp/src/containers/add-event.js
Labels: bug, frontend

#145 Fix uncorrect loading of some pages
  EventsExpress.Core/Services/EventService.cs
  EventsExpress.Core/Services/UserService.cs
Labels: bug, top

#150 #100 Events on home page filtered by favorite categories
  .gitignore
  EventsExpress.Core/DTOs/EventFilterViewModel.cs
  EventsExpress.Core/Extensions/AppHttpContext.cs
  EventsExpress.Core/Extensions/HttpContextExtensions.cs
  EventsExpress.Core/IServices/IEventService.cs
  EventsExpress.Core/Services/CategoryService.cs
  EventsExpress.Core/Services/EventService.cs
  EventsExpress.Db/EF/AppDbContext.cs
  EventsExpress.Db/Enums/EventStatus.cs
  EventsExpress.Db/Migrations/20201015163850_AddEventStatusHistory.cs
  EventsExpress.Test/ServiceTests/PhotoServiceTests.cs
  EventsExpress/.gitignore
  EventsExpress/ClientApp/.gitignore
  EventsExpress/ClientApp/package.json
  EventsExpress/ClientApp/src/App.js
  EventsExpress/ClientApp/src/actions/event-list.js
  EventsExpress/ClientApp/src/actions/login.js
  EventsExpress/ClientApp/src/actions/logout.js
  EventsExpress/ClientApp/src/components/Route guard/400.js
  EventsExpress/ClientApp/src/components/Route guard/404.js
  EventsExpress/ClientApp/src/components/app/app.js
  EventsExpress/ClientApp/src/components/chat/msg.js
  EventsExpress/ClientApp/src/components/chat/user_chats.js
  EventsExpress/ClientApp/src/components/comment/comment-item.js
  EventsExpress/ClientApp/src/components/comment/comment-list.js
  EventsExpress/ClientApp/src/components/event/event-cancel-modal.js
  EventsExpress/ClientApp/src/components/event/event-filter.js
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/event/event-item.js
  EventsExpress/ClientApp/src/components/event/event-list.js
  EventsExpress/ClientApp/src/components/header-profile/header-profile.js
  EventsExpress/ClientApp/src/components/helpers/eventHelper.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
  EventsExpress/ClientApp/src/components/home/home.js
  EventsExpress/ClientApp/src/components/layout/layout.js
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
  EventsExpress/ClientApp/src/components/notification_events/notification_events.js
  EventsExpress/ClientApp/src/components/profile/user-profile.js
  EventsExpress/ClientApp/src/components/user-info/User-info-card.js
  EventsExpress/ClientApp/src/components/users/user-item.js
  EventsExpress/ClientApp/src/components/users/users.js
  EventsExpress/ClientApp/src/containers/UserSearchFilterWrapper.js
  EventsExpress/ClientApp/src/containers/event-filter.js
  EventsExpress/ClientApp/src/containers/event-item-view.js
  EventsExpress/ClientApp/src/containers/event-list.js
  EventsExpress/ClientApp/src/containers/events-for-admin.js
  EventsExpress/ClientApp/src/containers/header-profile.js
  EventsExpress/ClientApp/src/containers/left-sidebar.js
  EventsExpress/ClientApp/src/containers/user-item-view.js
  EventsExpress/ClientApp/src/index.js
  EventsExpress/ClientApp/src/reducers/event-list.js
  EventsExpress/ClientApp/src/reducers/login.js
  EventsExpress/ClientApp/src/reducers/user.js
  EventsExpress/ClientApp/src/services/EventsExpressService.js
  EventsExpress/ClientApp/src/store/initialState.js
  EventsExpress/Controllers/EventController.cs
  EventsExpress/EventsExpress.csproj
  EventsExpress/Properties/launchSettings.json
  EventsExpress/Startup.cs
Labels: .NET, React, javascript, story

#152 100-hotfix-and-refactoring
  EventsExpress.Core/Services/AuthService.cs
  EventsExpress.Core/Services/EventService.cs
  EventsExpress/ClientApp/src/components/event/event-list.js
  EventsExpress/ClientApp/src/components/header-profile/header-profile.js
  EventsExpress/ClientApp/src/components/helpers/eventHelper.js
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
  EventsExpress/ClientApp/src/components/shared/pagePagination.js
  EventsExpress/ClientApp/src/containers/UserSearchFilterWrapper.js
  EventsExpress/ClientApp/src/containers/event-filter.js
  EventsExpress/ClientApp/src/containers/event-list.js
  EventsExpress/ClientApp/src/containers/events-for-admin.js
  EventsExpress/ClientApp/src/services/EventsExpressService.js
  EventsExpress/Controllers/EventController.cs
Labels: .NET, javascript

#159 Moving buttons Join/Leave, adding modal form for leaving event.
  EventsExpress/ClientApp/src/components/event/event-cancel-modal.js
  EventsExpress/ClientApp/src/components/event/event-item-view.css
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/event/event-leave-modal.js
  EventsExpress/Controllers/EventController.cs
Labels: frontend, javascript

#154 151 user doesn't see previously selected categories
  EventsExpress.Core/IServices/ICategoryService.cs
  EventsExpress.Core/Services/CategoryService.cs
  EventsExpress.Db/IRepo/ICategoryRepository.cs
  EventsExpress.Db/Repo/CategoryRepository.cs
  EventsExpress/ClientApp/src/actions/EditProfile/addUserCategory.js
  EventsExpress/ClientApp/src/actions/SelectCategories.js
  EventsExpress/ClientApp/src/components/Route guard/403.js
  EventsExpress/ClientApp/src/components/SelectCategories/SelectCategories.js
  EventsExpress/ClientApp/src/components/comment/comment-list.js
  EventsExpress/ClientApp/src/components/event/event-filter.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/event/event-item.js
  EventsExpress/ClientApp/src/components/event/event-list.js
  EventsExpress/ClientApp/src/components/event/events-for-profile.js
  EventsExpress/ClientApp/src/components/event/share/ShareButtons.js
  EventsExpress/ClientApp/src/components/event/share/SocialShareMenu.js
  EventsExpress/ClientApp/src/components/header-profile/header-profile.js
  EventsExpress/ClientApp/src/components/helpers/Alert.js
  EventsExpress/ClientApp/src/components/helpers/ImagePreview.js
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
  EventsExpress/ClientApp/src/components/profile/profile.js
  EventsExpress/ClientApp/src/components/profile/user-profile.js
  EventsExpress/ClientApp/src/components/users/user-item.js
  EventsExpress/ClientApp/src/components/users/users.js
  EventsExpress/ClientApp/src/containers/FacebookLogin.js
  EventsExpress/ClientApp/src/containers/GoogleLogin.js
  EventsExpress/ClientApp/src/containers/SelectCategories.js
  EventsExpress/ClientApp/src/containers/alert.js
  EventsExpress/ClientApp/src/containers/editProfileContainers/addUserCategoryContainer.js
  EventsExpress/ClientApp/src/containers/event-list.js
  EventsExpress/ClientApp/src/reducers/SelectCategories.js
  EventsExpress/ClientApp/src/reducers/root.js
  EventsExpress/ClientApp/src/reducers/user.js
  EventsExpress/ClientApp/src/services/EventsExpressService.js
  EventsExpress/Controllers/UsersController.cs
  EventsExpress/DTO/EditUserCategoriesDto.cs
  EventsExpress/Validation/CategoryDtoEnumerationValidation.cs
  EventsExpress/appsettings.Development.json
  EventsExpress/appsettings.json
Labels: React, Refactoring, javascript

#164 #157 - fix bug, user cannot change gender and date of birth. Cannot c…
  EventsExpress/ClientApp/src/containers/add-event.js
  EventsExpress/ClientApp/src/services/EventsExpressService.js
  EventsExpress/Controllers/UsersController.cs
  EventsExpress/DTO/EditUserBirthDto.cs
  EventsExpress/DTO/EditUserGenderDto.cs
  EventsExpress/DTO/EditUserNameDto.cs
  EventsExpress/Validation/EditUserBirthDtoValidator.cs
  EventsExpress/Validation/EditUserGenderDtoValidator.cs
  EventsExpress/Validation/EditUserNameDtoValidator.cs
Labels: bug

#203 Reccurent event migration fix
  EventsExpress.Core/NotificationHandlers/CreateEventVerificationHandler.cs
  EventsExpress.Db/Entities/ManageableEntity.cs
  EventsExpress.Db/Migrations/20201120091348_EditPropsManageableEvent.Designer.cs
  EventsExpress.Db/Migrations/20201120091348_EditPropsManageableEvent.cs
  EventsExpress.Db/Migrations/20201121093605_RenameTableEventSchedule.Designer.cs
  EventsExpress.Db/Migrations/20201121093605_RenameTableEventSchedule.cs
  EventsExpress.Db/Migrations/20201121113556_AddDefaultDatetimeValues.Designer.cs
  EventsExpress.Db/Migrations/20201121113556_AddDefaultDatetimeValues.cs
  EventsExpress.Db/Migrations/20201123094736_FixCreatedDateTime.cs
  EventsExpress.Db/Migrations/20201124092349_AddEventScheduleTable.Designer.cs
  EventsExpress.Db/Migrations/20201124092349_AddEventScheduleTable.cs
  EventsExpress.Db/Migrations/AppDbContextModelSnapshot.cs
Labels: bug, hotfix

#197 Edit font for buttons join and leave, fix bugs.
  EventsExpress/ClientApp/src/components/event/event-item-view.css
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/event/event-leave-modal.js
Labels: bug, frontend

#209 Fixed: inventories do not include when event create
  EventsExpress/ClientApp/src/services/EventsExpressService.js
  EventsExpress/Mapping/AutoMapperProfile.cs
Labels: bug, hotfix

#219 Add .yml with target diff coverage as 30%
  azurepipelines-coverage.yml
Labels: infrastructure

#218 Create Unit-tests for EventScheduleService
  Custom.ruleset
  EventsExpress.Core/DTOs/EventScheduleDTO.cs
  EventsExpress.Core/Services/EventScheduleService.cs
  EventsExpress.Test/ServiceTests/EventScheduleServiceTests.cs
  EventsExpress/ClientApp/src/components/event/event-item-view.js
Labels: test

#226 Writing unit test for PhotoService and EventService.
  EventsExpress.Test/ServiceTests/EventServiceTest.cs
  EventsExpress.Test/ServiceTests/PhotoServiceTests.cs
Labels: test
