Repository ita-social-projects/EventsExpress, pull requests merged in 2020-10, with the labels that each got.

#109 103 add code quality analyzers
  .editorconfig
  Directory.Build.props
  EventsExpress/ClientApp/.jshintrc
  EventsExpress/ClientApp/package-lock.json
  EventsExpress/ClientApp/package.json
  stylecop.json
Labels: back infrastructure, frontend

#108 83 integrate twitter auth
  .gitignore
  EventsExpress.Core/IServices/IAuthService.cs
  EventsExpress.Core/Services/AuthService.cs
  EventsExpress/.gitignore
  EventsExpress/ClientApp/.gitignore
  EventsExpress/ClientApp/package-lock.json
  EventsExpress/ClientApp/package.json
  EventsExpress/ClientApp/src/actions/login.js
  EventsExpress/ClientApp/src/actions/logout.js
  EventsExpress/ClientApp/src/components/Authentication/authentication.js
  EventsExpress/ClientApp/src/components/app/app.js
  EventsExpress/ClientApp/src/components/event/share/ShareButtons.js
  EventsExpress/ClientApp/src/components/login/login.js
  EventsExpress/ClientApp/src/config.js
  EventsExpress/ClientApp/src/containers/FacebookLogin.js
  EventsExpress/ClientApp/src/containers/GoogleLogin.js
  EventsExpress/ClientApp/src/containers/TwitterLogin.js
  EventsExpress/ClientApp/src/containers/css/Auth.css
  EventsExpress/ClientApp/src/containers/login.js
  EventsExpress/ClientApp/src/services/EventsExpressService.js
  EventsExpress/Controllers/AuthenticationController.cs
  EventsExpress/EventsExpress.xml
Labels: .NET, React, enhancement, javascript

#132 Migrate solution to .net core 3.1
  EventsExpress.Core/EventsExpress.Core.csproj
  EventsExpress.Db/EventsExpress.Db.csproj
  EventsExpress.Test/EventsExpress.Test.csproj
  EventsExpress.Test/ServiceTests/PhotoServiceTests.cs
  EventsExpress/EventsExpress.csproj
  EventsExpress/Startup.cs
Labels: .NET, enhancement

#134 Customize google button
  EventsExpress/ClientApp/src/containers/GoogleLogin.js
  EventsExpress/ClientApp/src/containers/css/Auth.css
Labels: bug

#138 Limiting the number of participants
  EventsExpress.Core/Services/EventService.cs
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
Labels: story

#141 Fix incorrect displaying categories from GetAllCategories
  EventsExpress.Core/Services/CategoryService.cs
Labels: bug
