Repository ita-social-projects/EventsExpress, pull requests merged in 2021-03, with the labels that each got.

#449 EF Entities configuration are divided into separate files.
  EventsExpress.Db/Configurations/CategoryConfiguration.cs
  EventsExpress.Db/Configurations/CommentsConfiguration.cs
  EventsExpress.Db/Configurations/EventCategoryConfiguration.cs
  EventsExpress.Db/Configurations/EventConfiguration.cs
  EventsExpress.Db/Configurations/EventOwnerConfiguration.cs
  EventsExpress.Db/Configurations/EventStatusHistoryConfiguration.cs
  EventsExpress.Db/Configurations/InventoryConfiguration.cs
  EventsExpress.Db/Configurations/NotificationTypeConfiguration.cs
  EventsExpress.Db/Configurations/RateConfiguration.cs
  EventsExpress.Db/Configurations/RelationshipConfiguration.cs
  EventsExpress.Db/Configurations/UnitOfMeasuringConfiguration.cs
  EventsExpress.Db/Configurations/UserCategoryConfiguration.cs
  EventsExpress.Db/Configurations/UserEventConfiguration.cs
  EventsExpress.Db/Configurations/UserEventInventoryConfiguration.cs
  EventsExpress.Db/Configurations/UserNotificationTypeConfiguration.cs
  EventsExpress.Db/EF/AppDbContext.cs
Labels: .NET, back infrastructure, improvement, refactoring

#454 Datepicker incorrect work
  EventsExpress/ClientApp/src/components/event/event-filter-status.js
  EventsExpress/ClientApp/src/components/event/event-filter.js
  EventsExpress/ClientApp/src/components/event/event-form.css
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
Labels: bug, frontend, react

#465 Photos migrations updated
  EventsExpress.Db/Migrations/20210322130148_Reports dropped from db.cs
  EventsExpress.Db/Migrations/20210322130148_reports dropped from db.Designer.cs
  EventsExpress.Db/Migrations/20210330123653_PhotosMigratedToBlobStorage.Designer.cs
  EventsExpress.Db/Migrations/20210330123653_PhotosMigratedToBlobStorage.cs
  EventsExpress.Db/Migrations/AppDbContextModelSnapshot.cs
Labels: bug
