Repository ita-social-projects/EventsExpress, pull requests merged in 2021-07, with the labels that each got.

#677 Refactor 'helpers.js' into separate components
  EventsExpress/ClientApp/src/components/SelectCategories/SelectCategories.js
  EventsExpress/ClientApp/src/components/category/category-edit.js
  EventsExpress/ClientApp/src/components/chat/chat.js
  EventsExpress/ClientApp/src/components/comment/comment-form.js
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-component.js
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-list-component.js
  EventsExpress/ClientApp/src/components/contactAdmin/renderIssuesList.js
  EventsExpress/ClientApp/src/components/event/event-filter.js
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/users-view.js
  EventsExpress/ClientApp/src/components/helpers/form-helpers/index.js
  EventsExpress/ClientApp/src/components/helpers/form-helpers/render-checkbox.jsx
  EventsExpress/ClientApp/src/components/helpers/form-helpers/render-phone-input.jsx
  EventsExpress/ClientApp/src/components/helpers/form-helpers/render-radio-button.jsx
  EventsExpress/ClientApp/src/components/helpers/form-helpers/render-select-field.jsx
  EventsExpress/ClientApp/src/components/helpers/form-helpers/render-text-area.jsx
  EventsExpress/ClientApp/src/components/helpers/form-helpers/render-text-field.jsx
  EventsExpress/ClientApp/src/components/helpers/get-age-string.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
  EventsExpress/ClientApp/src/components/helpers/simple-modal-with-details.js
  EventsExpress/ClientApp/src/components/helpers/validators/email-address-validator.js
  EventsExpress/ClientApp/src/components/helpers/validators/form-validators.js
  EventsExpress/ClientApp/src/components/helpers/validators/index.js
  EventsExpress/ClientApp/src/components/helpers/validators/min-max-length-validators.js
  EventsExpress/ClientApp/src/components/helpers/validators/number-fields-validator.js
  EventsExpress/ClientApp/src/components/helpers/validators/required-fields-validator.js
  EventsExpress/ClientApp/src/components/inventory/InventoryList.js
  EventsExpress/ClientApp/src/components/inventory/VisitorSeeItem.js
  EventsExpress/ClientApp/src/components/inventory/inventory-form-validator.js
  EventsExpress/ClientApp/src/components/inventory/inventory.js
  EventsExpress/ClientApp/src/components/inventory/ownerEditItem.js
  EventsExpress/ClientApp/src/components/inventory/ownerSeeItem.js
  EventsExpress/ClientApp/src/components/inventory/visitorTakeItem.js
  EventsExpress/ClientApp/src/components/login/login.js
  EventsExpress/ClientApp/src/components/notification_template/notification-template-form/notification-template-form.js
  EventsExpress/ClientApp/src/components/profile/editProfile/ChangePassword.jsx
  EventsExpress/ClientApp/src/components/profile/editProfile/editBirthday.js
  EventsExpress/ClientApp/src/components/profile/editProfile/editGender.js
  EventsExpress/ClientApp/src/components/recoverPassword/recoverPassword.js
  EventsExpress/ClientApp/src/components/register/register-complete.jsx
  EventsExpress/ClientApp/src/components/register/register.js
  EventsExpress/ClientApp/src/components/tracks/tracks-filter.js
  EventsExpress/ClientApp/src/components/unitOfMeasuring/unitOfMeasuring-edit.js
  EventsExpress/ClientApp/src/components/user-info/User-info-card.js
  EventsExpress/ClientApp/src/components/users/UserSearchFilter.js
  EventsExpress/ClientApp/src/components/users/UsersFilters.js
  EventsExpress/ClientApp/src/containers/edit-event-from-parent.js
  EventsExpress/ClientApp/src/containers/edit-event.js
  EventsExpress/ClientApp/src/containers/event-draft.js
  EventsExpress/ClientApp/src/containers/event-edit-validate-form .js
  EventsExpress/ClientApp/src/containers/event-validate-form.js
Labels: frontend, refactoring

#687 Fixed pagination on event-card
  EventsExpress/ClientApp/src/components/event/RenderList.js
  EventsExpress/ClientApp/src/components/event/event-list.js
Labels: bug, react

#684 Displaying all categories on event card
  EventsExpress/ClientApp/src/components/event/event-item.js
Labels: frontend, react

#693 App working resumed
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-component.js
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-filter-component.js
  EventsExpress/ClientApp/src/constants/issue-status-enum.js
  EventsExpress/ClientApp/src/constants/issue-type-enum.js
  EventsExpress/ClientApp/src/containers/contactAdmin/contactAdmin-details-container.js
Labels: High, bug, hotfix

#691 Improve work radiobutton in form of sending location data
  EventsExpress/ClientApp/src/components/event/event-form.js
Labels: improvement, javascript

#678 Improve photo upload logic
  EventsExpress.Core/IServices/IPhotoservice.cs
  EventsExpress.Core/Services/EventService.cs
  EventsExpress.Core/Services/PhotoService.cs
  EventsExpress.Test/ControllerTests/EventControllerTests.cs
  EventsExpress.Test/ControllerTests/UsersControllerTests.cs
  EventsExpress.Test/ServiceTests/EventServiceTest.cs
  EventsExpress.Test/ServiceTests/PhotoServiceTests.cs
  EventsExpress.Test/ValidatorTests/PhotoValidatorTests.cs
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/helpers/DropZoneField.js
  EventsExpress/ClientApp/src/components/helpers/ImagePreview.js
  EventsExpress/ClientApp/src/components/helpers/form-helpers/render-field-error.jsx
  EventsExpress/ClientApp/src/components/helpers/helpers.css
  EventsExpress/ClientApp/src/constants/EventLocationType.js
  EventsExpress/ClientApp/src/containers/async-validate-photo.js
  EventsExpress/ClientApp/src/containers/event-edit-validate-form .js
  EventsExpress/ClientApp/src/services/EventService.js
  EventsExpress/ClientApp/src/services/PhotoService.js
  EventsExpress/ClientApp/src/services/UserService.js
  EventsExpress/Controllers/EventController.cs
  EventsExpress/Controllers/UsersController.cs
  EventsExpress/Mapping/EventMapperProfile.cs
  EventsExpress/Validation/PhotoValidator.cs
  EventsExpress/ViewModels/EventEditViewModel.cs
  EventsExpress/ViewModels/PhotoViewModel.cs
Labels: .NET, epic-0, improvement

#710 Delete unnecessary symbols from email link
  EventsExpress.Core/NotificationHandlers/RegisterVerificationHandler.cs
Labels: bug
