Repository ita-social-projects/EventsExpress, pull requests merged in 2021-02, with the labels that each got.

#395 Сhanged "Comuna" icon
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
Labels: improvement

#396 Moved button 'Write' from user avatar to bottom.
  EventsExpress/ClientApp/src/components/profile/User-profile.css
  EventsExpress/ClientApp/src/components/profile/user-profile.js
Labels: frontend, good first issue

#400 #351 Fixed: incorrect location of dropdown in contact us
  EventsExpress/ClientApp/src/components/contactUs/contactUs.js
  EventsExpress/ClientApp/src/components/inventory/InventoryHeaderButton.js
  EventsExpress/ViewModels/PageViewModel.cs
Labels: bug

#401 Fixed date picker incorrectly drops
  EventsExpress/ClientApp/src/components/event/event-form.css
Labels: bug

#413 added frontend validation for small photos
  EventsExpress/ClientApp/src/actions/EditProfile/change-avatar.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
  EventsExpress/ClientApp/src/components/profile/editProfile/change-avatar.js
  EventsExpress/ClientApp/src/containers/editProfileContainers/change-avatar.js
Labels: bug
