Repository ita-social-projects/EventsExpress, pull requests merged in 2021-04, with the labels that each got.

#467 Divide events routes
  EventsExpress/ClientApp/src/actions/user/user-item-view-action.js
  EventsExpress/ClientApp/src/components/Route guard/css/error.css
  EventsExpress/ClientApp/src/components/event/events-for-profile.js
  EventsExpress/ClientApp/src/components/profile/User-profile.css
  EventsExpress/ClientApp/src/components/profile/events.js
  EventsExpress/ClientApp/src/components/profile/user-profile.js
  EventsExpress/ClientApp/src/containers/user-item-view.js
  EventsExpress/ClientApp/src/index.js
Labels: frontend, improvement, react

#443 Event filtering due to location
  EventsExpress.Core/DTOs/EventFilterViewModel.cs
  EventsExpress.Core/EventsExpress.Core.csproj
  EventsExpress.Core/Services/EventService.cs
  EventsExpress.Db/Entities/EventLocation.cs
  EventsExpress.Test/ServiceTests/EventServiceTest.cs
  EventsExpress.Test/ServiceTests/TestClasses/Event/GetEventExistingId.cs
  EventsExpress/ClientApp/src/components/event/event-filter-status.js
  EventsExpress/ClientApp/src/components/event/event-filter.js
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/map-modal.js
  EventsExpress/ClientApp/src/components/event/map/display-map.js
  EventsExpress/ClientApp/src/components/event/map/location-map.js
  EventsExpress/ClientApp/src/components/event/slider.css
  EventsExpress/ClientApp/src/components/helpers/eventHelper.js
  EventsExpress/ClientApp/src/containers/add-event.js
  EventsExpress/ClientApp/src/containers/event-filter.js
  EventsExpress/EventsExpress.csproj
Labels: story

#474 #470-Approve as an owner button action has been fixed
  EventsExpress/ClientApp/src/components/event/event-item-view.js
Labels: bug

#478 Auth security
  EventsExpress.Test/PoliciesTests/RoleHanlderTest.cs
  EventsExpress/ClientApp/src/actions/authUser.js
  EventsExpress/ClientApp/src/actions/modalWind-action.js
  EventsExpress/ClientApp/src/components/Route guard/401.js
  EventsExpress/ClientApp/src/components/admin/admin.js
  EventsExpress/ClientApp/src/components/app/app.js
  EventsExpress/ClientApp/src/components/category/categories.js
  EventsExpress/ClientApp/src/components/header-profile/header-profile.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
  EventsExpress/ClientApp/src/components/login/login.js
  EventsExpress/ClientApp/src/components/unitOfMeasuring/unitsOfMeasuring.js
  EventsExpress/ClientApp/src/constants/userRoles.js
  EventsExpress/ClientApp/src/containers/UsersWrapper.js
  EventsExpress/ClientApp/src/containers/header-profile.js
  EventsExpress/ClientApp/src/containers/users.js
  EventsExpress/ClientApp/src/index.js
  EventsExpress/ClientApp/src/security/authComponent.js
  EventsExpress/ClientApp/src/security/withAuthRedirect.js
  EventsExpress/ClientApp/src/services/AuthenticationService.js
  EventsExpress/ClientApp/src/store/configureStore.js
  EventsExpress/Controllers/CategoryController.cs
  EventsExpress/Controllers/CommentController.cs
  EventsExpress/Controllers/EventController.cs
  EventsExpress/Controllers/EventStatusHistoryController.cs
  EventsExpress/Controllers/InventoryController.cs
  EventsExpress/Controllers/NotificationTypeController.cs
  EventsExpress/Controllers/OwnersController.cs
  EventsExpress/Controllers/RolesController.cs
  EventsExpress/Controllers/UnitOfMeasuringController.cs
  EventsExpress/Controllers/UserEventInventoryController.cs
  EventsExpress/Controllers/UsersController.cs
  EventsExpress/Policies/PolicyNames.cs
  EventsExpress/Policies/RoleHandler.cs
  EventsExpress/Policies/RoleRequirement.cs
  EventsExpress/Startup.cs
Labels: improvement, infrastructure

#512 Negative value of participants fixed
  EventsExpress/ClientApp/src/actions/event/event-add-action.js
  EventsExpress/ClientApp/src/actions/event/event-item-view-action.js
Labels: bug

#510 Filter events through query string
  EventsExpress/ClientApp/src/components/helpers/eventHelper.js
  EventsExpress/ClientApp/src/containers/event-filter.js
  EventsExpress/ClientApp/src/containers/event-list.js
Labels: bug, refactoring

#538 UsersWrapper refactored
  EventsExpress/ClientApp/src/components/admin/admin.js
  EventsExpress/ClientApp/src/containers/UsersWrapper.js
  EventsExpress/ClientApp/src/containers/users.js
Labels: refactoring

#539 Fixed pagination in events
  EventsExpress/ClientApp/src/components/event/event-list.js
Labels: bug

#543 Hotfix: added roles including
  EventsExpress.Core/Services/UserService.cs
  EventsExpress.Test/ControllerTests/UsersControllerTests.cs
  EventsExpress/Controllers/UsersController.cs
Labels: bug, hotfix

#546 Fix bug with test cases
  EventsExpress.Test/ServiceTests/EventServiceTest.cs
  EventsExpress.Test/ServiceTests/TestClasses/Event/GetEventExistingId.cs
Labels: bug, test

#552 #476 Implement the ability to delete an event draft
  EventsExpress.Db/Configurations/EventConfiguration.cs
  EventsExpress.Db/Enums/EventStatus.cs
  EventsExpress.Test/ServiceTests/CommentServiceTests.cs
  EventsExpress.Test/ServiceTests/EventScheduleServiceTests.cs
  EventsExpress.Test/ServiceTests/InventoryServiceTest.cs
  EventsExpress.Test/ServiceTests/UserEventInventoryServiceTest.cs
  EventsExpress/ClientApp/src/actions/event/event-add-action.js
  EventsExpress/ClientApp/src/components/Draft/Draft-list.js
  EventsExpress/ClientApp/src/components/Draft/DraftEventCard.js
  EventsExpress/ClientApp/src/components/event/event-form.css
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/event/event-item.js
  EventsExpress/ClientApp/src/constants/eventStatusEnum.js
  EventsExpress/ClientApp/src/containers/css/Draft.css
  EventsExpress/ClientApp/src/containers/edit-event.js
  EventsExpress/ClientApp/src/containers/event-draft.js
Labels: enhancement, story

#563 Fixed issue with displaying long comments
  EventsExpress/ClientApp/src/components/comment/Comment.css
Labels: bug, frontend
