Repository ita-social-projects/EventsExpress, pull requests merged in 2021-06, with the labels that each got.

#616 #587 Move configs from front to backend
  .gitignore
  EventsExpress.Test/ControllerTests/FrontConfigControllerTest.cs
  EventsExpress/ClientApp/src/actions/config/get-configs-action.js
  EventsExpress/ClientApp/src/components/app/app.js
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-component.js
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-filter-component.js
  EventsExpress/ClientApp/src/components/event/share/ShareButtons.js
  EventsExpress/ClientApp/src/components/login/login.js
  EventsExpress/ClientApp/src/config.js
  EventsExpress/ClientApp/src/containers/FacebookLogin.js
  EventsExpress/ClientApp/src/containers/GoogleLogin.js
  EventsExpress/ClientApp/src/containers/contactAdmin/contactAdmin-details-container.js
  EventsExpress/ClientApp/src/containers/linked-auths-wrapper.js
  EventsExpress/ClientApp/src/containers/linked-auths/facebook-login-add-wrapper.js
  EventsExpress/ClientApp/src/containers/linked-auths/google-login-add-wrapper.js
  EventsExpress/ClientApp/src/containers/linked-auths/twitter-login-base.js
  EventsExpress/ClientApp/src/reducers/config.js
  EventsExpress/ClientApp/src/reducers/root.js
  EventsExpress/ClientApp/src/services/ConfigService.js
  EventsExpress/ClientApp/src/services/index.js
  EventsExpress/ClientApp/src/store/initialState.js
  EventsExpress/Controllers/FrontConfigsController.cs
  EventsExpress/Startup.cs
  EventsExpress/ViewModels/FrontConfigsViewModel.cs
  EventsExpress/appsettings.json
Labels: frontend, improvement

#621 CanChangePassword logic fixed
  EventsExpress.Core/Services/AuthService.cs
  EventsExpress.Test/ControllerTests/AuthenticationControllerTests.cs
  EventsExpress.Test/MapperTests/UserMapperProfileTests.cs
  EventsExpress.Test/ServiceTests/AuthServiceTests.cs
  EventsExpress.Test/ValidatorTests/ChangePasswordViewModelValidatorTests.cs
  EventsExpress.Test/ValidatorTests/EventValidatorTests.cs
  EventsExpress/ClientApp/src/components/profile/editProfile/ChangePassword.jsx
  EventsExpress/Mapping/UserMapperProfile.cs
  EventsExpress/Validation/ChangePasswordViewModelValidator.cs
  EventsExpress/ValueResolvers/UserChangePasswordResolver.cs
Labels: bug, frontend

#629 Profile page wrong data shows fixed
  EventsExpress.Core/Services/UserService.cs
  EventsExpress.Test/MapperTests/UserMapperProfileTests.cs
  EventsExpress/Mapping/UserMapperProfile.cs
  EventsExpress/ValueResolvers/ProfileToAttitudeResolver.cs
  EventsExpress/ValueResolvers/ProfileToRatingResolver.cs
Labels: bug

#647 Fixed "submit" button in change avatar field
  EventsExpress/ClientApp/src/actions/redactProfile/avatar-change-action.js
  EventsExpress/ClientApp/src/components/avatar/custom-avatar.js
  EventsExpress/ClientApp/src/components/profile/editProfile/change-avatar.js
  EventsExpress/ClientApp/src/reducers/editReducers/change_avatar.js
  EventsExpress/ClientApp/src/services/PhotoService.js
  EventsExpress/ClientApp/src/services/UserService.js
  EventsExpress/ClientApp/src/store/initialState.js
  EventsExpress/Controllers/UsersController.cs
Labels: High, bug, javascript

#643 The '+' sign has been replaced with the 'Add category' caption on the Categories admin panel
  EventsExpress/ClientApp/src/components/category/category-list.js
  EventsExpress/ClientApp/src/components/event/RenderList.js
  EventsExpress/ClientApp/src/containers/categories/category-add.js
Labels: Low, bug, frontend, react

#654 Fix correct answer from backend if password was input incorrectly
  EventsExpress.Core/Services/AuthService.cs
  EventsExpress.Test/ServiceTests/AuthServiceTests.cs
  EventsExpress/Filters/EventsExpressExceptionFilterAttribute.cs
Labels: .NET, bug, frontend

#671 The type of FrontConfigsController's action is explicitly specified. …
  EventsExpress/Controllers/FrontConfigsController.cs
Labels: .NET, bug, hotfix

#676 Login work resumed
  EventsExpress/ClientApp/src/actions/config/get-config-action.js
  EventsExpress/ClientApp/src/actions/config/get-configs-action.js
  EventsExpress/ClientApp/src/components/Draft/DraftEventCard.js
  EventsExpress/ClientApp/src/components/NavItem/NavItem.js
  EventsExpress/ClientApp/src/components/app/app.js
  EventsExpress/ClientApp/src/components/category/category-edit.js
  EventsExpress/ClientApp/src/components/category/category-item.js
  EventsExpress/ClientApp/src/components/chat/msg.js
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-item-component.js
  EventsExpress/ClientApp/src/components/event/approved-users-action.js
  EventsExpress/ClientApp/src/components/event/event-active-status.js
  EventsExpress/ClientApp/src/components/event/event-item-header.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/event/event-item.js
  EventsExpress/ClientApp/src/components/event/owners-action.js
  EventsExpress/ClientApp/src/components/event/share/ShareButtons.js
  EventsExpress/ClientApp/src/components/event/share/SocialShareMenu.js
  EventsExpress/ClientApp/src/components/event/users-view.js
  EventsExpress/ClientApp/src/components/eventSchedule/eventSchedule-popover.js
  EventsExpress/ClientApp/src/components/google-login/google-login.jsx
  EventsExpress/ClientApp/src/components/google-login/index.js
  EventsExpress/ClientApp/src/components/header-profile/header-profile.js
  EventsExpress/ClientApp/src/components/inventory/InventoryHeaderButton.js
  EventsExpress/ClientApp/src/components/inventory/InventoryList.js
  EventsExpress/ClientApp/src/components/inventory/VisitorSeeItem.js
  EventsExpress/ClientApp/src/components/inventory/inventory.js
  EventsExpress/ClientApp/src/components/inventory/ownerEditItem.js
  EventsExpress/ClientApp/src/components/inventory/ownerSeeItem.js
  EventsExpress/ClientApp/src/components/inventory/visitorTakeItem.js
  EventsExpress/ClientApp/src/components/left-sidebar/left-sidebar.js
  EventsExpress/ClientApp/src/components/login/login.js
  EventsExpress/ClientApp/src/components/profile/editProfile/linked-auths.jsx
  EventsExpress/ClientApp/src/components/profile/user-profile.js
  EventsExpress/ClientApp/src/components/rating/rating-average.js
  EventsExpress/ClientApp/src/components/tracks/track-item.js
  EventsExpress/ClientApp/src/components/unitOfMeasuring/unitOfMeasuring-edit.js
  EventsExpress/ClientApp/src/components/unitOfMeasuring/unitOfMeasuring-item.js
  EventsExpress/ClientApp/src/components/user-info/User-info-card.js
  EventsExpress/ClientApp/src/components/user-info/user-block.js
  EventsExpress/ClientApp/src/components/user-info/user-role-display.js
  EventsExpress/ClientApp/src/components/user-info/user-role-edit.js
  EventsExpress/ClientApp/src/containers/FacebookLogin.js
  EventsExpress/ClientApp/src/containers/GoogleLogin.js
  EventsExpress/ClientApp/src/containers/categories/category-item.js
  EventsExpress/ClientApp/src/containers/delete-comment.js
  EventsExpress/ClientApp/src/containers/event-draft.js
  EventsExpress/ClientApp/src/containers/linked-auths-wrapper.js
  EventsExpress/ClientApp/src/containers/linked-auths/facebook-login-add-wrapper.js
  EventsExpress/ClientApp/src/containers/linked-auths/google-login-add-wrapper.js
  EventsExpress/ClientApp/src/containers/linked-auths/local-login-add-wrapper.js
  EventsExpress/ClientApp/src/containers/linked-auths/twitter-login-base.js
  EventsExpress/ClientApp/src/containers/unitsOfMeasuring/unitOfMeasuring-add.js
  EventsExpress/ClientApp/src/containers/unitsOfMeasuring/unitOfMeasuring-item.js
  EventsExpress/ClientApp/src/reducers/config.js
  EventsExpress/ClientApp/src/services/ConfigService.js
  EventsExpress/ClientApp/src/services/EventsExpressService.js
  EventsExpress/ClientApp/src/store/initialState.js
Labels: High, bug, frontend, hotfix, javascript

#681 Fixed Issue view pagination
  EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-details-component.js
Labels: bug, frontend
