Repository ita-social-projects/EventsExpress, pull requests merged in 2021-01, with the labels that each got.

#378 Fix Wrong Alignment Of The UserName in profile
  EventsExpress/ClientApp/src/components/header-profile/header-profile.css
  EventsExpress/ClientApp/src/components/header-profile/header-profile.js
Labels: bug

#379 Fixed: The rating of the event attended is not saved
  EventsExpress/ClientApp/src/actions/rating.js
  EventsExpress/ClientApp/src/containers/rating.js
  EventsExpress/ClientApp/src/services/EventService.js
Labels: bug

#372 Cleanup after SonarCloud has been configured [skip ci]
  .github/pull_request_template.md
  .github/workflows/build.yml
  azurepipelines-coverage.yml
Labels: infrastructure

#384 #353 same dimensions cards
  EventsExpress.Core/Extensions/FormFileExtensions.cs
  EventsExpress.Core/Services/PhotoService.cs
  EventsExpress.Test/ServiceTests/PhotoServiceTests.cs
  EventsExpress/ClientApp/package.json
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/event-item-view.css
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/event/event-item.css
  EventsExpress/ClientApp/src/components/event/event-item.js
  EventsExpress/ClientApp/src/components/event/image-resizer.css
  EventsExpress/ClientApp/src/components/event/image-resizer.js
  EventsExpress/ClientApp/src/components/helpers/DropZoneField.js
  EventsExpress/ClientApp/src/components/profile/editProfile/change-avatar.js
  EventsExpress/ClientApp/src/components/profile/profile.js
  EventsExpress/ClientApp/src/containers/editProfileContainers/change-avatar.js
  EventsExpress/Startup.cs
Labels: Improvement, requirements

#387 Hotfix: added react-confirm-alert npm module
  EventsExpress/ClientApp/package.json
Labels: bug, hotfix

#390 #361 drop zone field validation
  EventsExpress/ClientApp/src/actions/add-comment.js
  EventsExpress/ClientApp/src/actions/add-event.js
  EventsExpress/ClientApp/src/components/category/category-edit.js
  EventsExpress/ClientApp/src/components/helpers/DropZoneField.js
  EventsExpress/ClientApp/src/components/helpers/Placeholder.js
  EventsExpress/ClientApp/src/components/helpers/ShowError.js
  EventsExpress/ClientApp/src/components/helpers/helpers.js
  EventsExpress/ClientApp/src/components/layout/layout.css
  EventsExpress/ClientApp/src/containers/add-event.js
  EventsExpress/ClientApp/src/containers/edit-event.js
Labels: bug
