Repository ita-social-projects/EventsExpress, pull requests merged in 2021-05, with the labels that each got.

#570 #560 Implement the ability to edit a published event in the special edit form
  EventsExpress/ClientApp/src/components/Draft/DraftEventCard.js
  EventsExpress/ClientApp/src/components/app/app.js
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/containers/edit-event.js
  EventsExpress/ClientApp/src/containers/event-draft.js
  EventsExpress/ClientApp/src/containers/event-edit-wrapper.js
Labels: frontend, improvement, story

#577 Replaced label "Send message…" with "Type your message..."
  EventsExpress/ClientApp/src/components/chat/chat.js
Labels: bug, frontend

#581 The swagger bug has fixed
  EventsExpress/EventsExpress.csproj
Labels: .NET, bug, hotfix

#582 Fixed issue with Bad request while changing gender
  EventsExpress/ClientApp/src/actions/redactProfile/avatar-change-action.js
  EventsExpress/ClientApp/src/actions/redactProfile/birthday-edit-action.js
  EventsExpress/ClientApp/src/actions/redactProfile/gender-edit-action.js
  EventsExpress/ClientApp/src/components/event/event-item-view.js
  EventsExpress/ClientApp/src/components/profile/editProfile/editBirthday.js
  EventsExpress/ClientApp/src/components/profile/editProfile/editGender.js
  EventsExpress/ClientApp/src/components/profile/editProfile/editUsername.js
  EventsExpress/ClientApp/src/components/register/register-complete.jsx
  EventsExpress/ClientApp/src/constants/GenderConstants.js
  EventsExpress/ClientApp/src/reducers/user.js
  EventsExpress/ClientApp/src/services/UserService.js
  EventsExpress/Validation/EditUserGenderViewModelValidator.cs
Labels: .NET, bug, hotfix, react

#584 fix redirect to event
  EventsExpress/ClientApp/src/actions/event/event-add-action.js
Labels: bug

#580 Divided logic of GetById & PasswordHasher as Service
  EventsExpress.Core/IServices/IAuthService.cs
  EventsExpress.Core/Services/AccountService.cs
  EventsExpress.Core/Services/AuthService.cs
  EventsExpress.Core/Services/EventScheduleService.cs
  EventsExpress.Core/Services/EventService.cs
  EventsExpress.Core/Services/EventStatusHistoryService.cs
  EventsExpress.Core/Services/PasswordHasherService.cs
  EventsExpress.Core/Services/SecurityContextService.cs
  EventsExpress.Db/Bridge/IPasswordHasher.cs
  EventsExpress.Db/Bridge/ISecurityContext.cs
  EventsExpress.Db/DbInitialize/DbInitializer.cs
  EventsExpress.Db/EF/AppDbContext.cs
  EventsExpress.Test/ConnectionFactory.cs
  EventsExpress.Test/ControllerTests/AccountControllerTests.cs
  EventsExpress.Test/ControllerTests/AuthenticationControllerTests.cs
  EventsExpress.Test/ControllerTests/ChatControllerTests.cs
  EventsExpress.Test/ControllerTests/EventControllerTests.cs
  EventsExpress.Test/ControllerTests/UsersControllerTests.cs
  EventsExpress.Test/MapperTests/EventMapperProfileTests.cs
  EventsExpress.Test/MapperTests/UserMapperProfileTests.cs
  EventsExpress.Test/ServiceTests/AccountServiceTests.cs
  EventsExpress.Test/ServiceTests/AuthServiceTests.cs
  EventsExpress.Test/ServiceTests/EventScheduleServiceTests.cs
  EventsExpress.Test/ServiceTests/EventServiceTest.cs
  EventsExpress.Test/ServiceTests/EventStatusHistoryServiceTest.cs
  EventsExpress.Test/ServiceTests/PasswordHasherServiceTests.cs
  EventsExpress.Test/ServiceTests/SecurityContextServiceTests.cs
  EventsExpress/ChatHub/ChatRoom.cs
  EventsExpress/Controllers/AccountController.cs
  EventsExpress/Controllers/AuthenticationController.cs
  EventsExpress/Controllers/ChatController.cs
  EventsExpress/Controllers/EventController.cs
  EventsExpress/Controllers/UsersController.cs
  EventsExpress/Mapping/RegisterMapperProfile.cs
  EventsExpress/Program.cs
  EventsExpress/Startup.cs
  EventsExpress/ValueResolvers/EventDtoToOwnersResolver.cs
  EventsExpress/ValueResolvers/EventDtoToVisitorsResolver.cs
  EventsExpress/ValueResolvers/RegisterDtoToAccountResolver.cs
  EventsExpress/ValueResolvers/UserToAttitudeResolver.cs
Labels: .NET, refactoring

#585 Move sensitive configs over to Azure key-vault
  .gitignore
  EventsExpress.Core/Infrastructure/JwtOptionsModel.cs
  EventsExpress/EventsExpress.csproj
  EventsExpress/Program.cs
  EventsExpress/appsettings.json
Labels: .NET, improvement

#576 Fixed issue with saving published event after editing. Divided logic of LocationMap
  EventsExpress/ClientApp/src/actions/event/event-add-action.js
  EventsExpress/ClientApp/src/components/Draft/Draft-list.js
  EventsExpress/ClientApp/src/components/app/app.js
  EventsExpress/ClientApp/src/components/event/event-filter.js
  EventsExpress/ClientApp/src/components/event/event-form.js
  EventsExpress/ClientApp/src/components/event/map-modal.js
  EventsExpress/ClientApp/src/components/event/map/location-map.js
  EventsExpress/ClientApp/src/components/header-profile/header-profile.js
  EventsExpress/ClientApp/src/components/helpers/form-helpers/index.js
  EventsExpress/ClientApp/src/components/helpers/form-helpers/location-map-with-circle.jsx
  EventsExpress/ClientApp/src/components/helpers/form-helpers/location-map-with-marker.jsx
  EventsExpress/ClientApp/src/components/helpers/form-helpers/location-map.jsx
  EventsExpress/ClientApp/src/containers/add-event.js
  EventsExpress/ClientApp/src/containers/edit-event.js
  EventsExpress/ClientApp/src/containers/event-draft.js
  EventsExpress/ClientApp/src/containers/event-filter.js
  EventsExpress/ClientApp/src/containers/header-profile.js
  EventsExpress/ClientApp/src/services/EventService.js
Labels: bug, frontend, hotfix, improvement, react, refactoring

#612 Remove app http context
  EventsExpress.Core/Extensions/AppHttpContext.cs
  EventsExpress.Core/Extensions/HttpContextExtensions.cs
  EventsExpress.Core/Infrastructure/AppBaseUrlModel.cs
  EventsExpress.Core/NotificationHandlers/CreateEventVerificationHandler.cs
  EventsExpress.Core/NotificationHandlers/EventCreatedHandler.cs
  EventsExpress.Core/NotificationHandlers/EventStatusHandler.cs
  EventsExpress.Core/NotificationHandlers/ParticipationHandler.cs
  EventsExpress.Core/NotificationHandlers/RegisterVerificationHandler.cs
  EventsExpress.Core/Services/PhotoService.cs
  EventsExpress.Test/HandlerTests/CreateEventVerificationHandlerTests.cs
  EventsExpress.Test/HandlerTests/EventCreatedHandlerTests.cs
  EventsExpress.Test/HandlerTests/EventStatusHandlerTests.cs
  EventsExpress.Test/HandlerTests/ParticipationHandlerTests.cs
  EventsExpress.Test/HandlerTests/RegisterVerificationHandlerTests.cs
  EventsExpress/Startup.cs
  EventsExpress/appsettings.json
Labels: .NET, refactoring
